[supremacy]
# Time limit in seconds:
time-limit = 480
# Set to true for fullscreen:
fullscreen = false
# Set to True for high contrast mode:
high-contrast = false
# Set to > 1 to artificially increase crystal production:
crystal-boost = 10
# Uncomment and set to a number to always generate the same map:
# seed = 123

# --- Select bots for the game ---
# Use your bot:
[[bot]]
package = "your_bot"

# Add a number of extra bots:
# Override the name and color to distinguish them in the game.
[[bot]]
package = "template"
override = { name = "Bottiglia", color = "#00ff00" }

[[bot]]
package = "template"
override = { name = "Botulf", color = "#00aaa0" }
